stages:
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: telstrapoc:latest
      registry: 127.0.0.1:34115
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
